main/urls.py
from main.models import CarReserv
from . import views
from django.urls import path
from .views import UloaxView,  CarReservView, AboutView, RegistationView, BookHistoryView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'main'

urlpatterns = [
    path('', UloaxView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('booking/', CarReservView.as_view(), name='booking'),
    path('registration/', RegistationView.as_view(), name = 'registration'),
    path('login/', LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('history/', BookHistoryView.as_view(), name='history')
]

uloax/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('uloax/', include ('main.urls')),
]

main/models.py
from django.db import models
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from random import randint

RATE = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
)

class Rate(models.Model):
    rate1 = models.IntegerField(choices=RATE)
    date_created = models.DateTimeField(default=timezone.now,editable=False)

    def __str__(self):
        return str(self.rate)

class Car(models.Model):
    car_model = models.CharField(max_length = 30)
    car_color = models.CharField (max_length = 20)
    has_ac = models.BooleanField()
    date_created = models.DateTimeField(default=timezone.now,editable=False)
    booked = models.DateTimeField(default=timezone.now,editable=False)
    
    def __str__(self):
        return str(self.car_model)

class CarReserv(models.Model):
    client = models.ForeignKey(User, on_delete = models.CASCADE)
    from_destination = models.CharField(max_length = 100)
    to_destination = models.CharField(max_length =100)
    price = models.SmallIntegerField()
    duration = models.CharField(max_length = 50, default=randint(10, 30))
    passangers = models.SmallIntegerField()
    car = models.ForeignKey(Car, on_delete=models.CASCADE) 
    date_created = models.DateTimeField(default=timezone.now,editable=False)

    def __str__(self):
        return str(self.date_created)

class Driver(models.Model):
    user = models.OneToOneField(CarReserv, on_delete=models.CASCADE)
    experience = models.SmallIntegerField()
    phone_number = models.CharField(max_length=20)
    rates = models.ManyToManyField(Rate)
    date_created = models.DateTimeField(default=timezone.now,editable=False)

    def __str__(self):
        return str(self.user)

class UserCreate(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    password = models.SmallIntegerField()
    conf_password = models.SmallIntegerField()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import ModelForm
from .models import CarReserv
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class CarReservCreationForm(ModelForm):
    class Meta:
        model = CarReserv
        fields = ('from_destination','to_destination','passangers',)

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        }
        )
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }
        )
    )

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Password'
        }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
            'class': 'form-control',
            'placeholder': 'Confirm Password'
        }
        )
    )

    class Meta:
        model = User
        fields = ('first_name','last_name','email','username','password1','password2',)

###############################################
###############################################

class ContactForm(forms.Form):

    name = forms.CharField(max_length=120)
    email = forms.EmailField()
    inquiry = forms.CharField(max_length=70)
    message = forms.CharField(widget=forms.Textarea)

    def get_info(self):
        cl_data = super().clean()

        name = cl_data.get('name').strip()
        from_email = cl_data.get('email')
        subject = cl_data.get('inquiry')

        msg = f'{name} with email {from_email} said:'
        msg += f'\n"{subject}"\n\n'
        msg += cl_data.get('message')

        return subject, msg

    def send(self):

        subject, msg = self.get_info()

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]
        )

main/views.py
from django.shortcuts import render
from django.views.generic import ListView, View
from .models import Car, CarReserv, Driver, Rate
from .forms import CarReservCreationForm, CustomUserCreationForm
from django.contrib.auth.models import User
from random import randint
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages 
from datetime import datetime, timedelta
from django.core.mail import send_mail
from django.conf import settings

class UloaxView(View):
    def get(self, request):
        return render(request=request, template_name='main/taxi_plans.html')

    def post(self, request):
        return render(request=request, template_name='main/book_history.html')

class AboutView(View):
    def get(self, request):
        return render(request=request, template_name='main/about.html')
    
    def post(self, request):
        if "searchreserv" in request.POST:
            startdate_form = request.POST.get('startdate')
            enddate_form = request.POST.get('enddate')

            startdate = datetime.strptime(startdate_form, '%Y-%m-%d')
            enddate = datetime.strptime(enddate_form, '%Y-%m-%d')

            history_reserv = CarReserv.objects.filter(date_created__range=[startdate, enddate])

            return render(request=request, template_name='main/book_history.html', context={'reservs':history_reserv})

        else:
            subject = 'Click here'
            message = "Congratulations, you have successfully subscribed to the newsletter."
            recipient = request.POST.get('email')

            send_mail(subject, message,
                      settings.DEFAULT_FROM_EMAIL, [recipient])
            
            return render(request=request, template_name='main/about.html')

class CarView(ListView):
    model = Car

class CarReservView(LoginRequiredMixin,View):
    model = CarReserv
    template_name = 'main/booking.html'
    form_class = CarReservCreationForm

    def get(self, request):
        carreserv_creation_form = CarReservCreationForm()
        return render(
            request=request,
             template_name='main/booking.html', 
             context={'sign_in_form': carreserv_creation_form,'title': 'Booking'})


    def post(self,request):
        if "booking" in request.POST:
            carreserv_creation_form = CarReservCreationForm(request.POST)

            print(carreserv_creation_form.errors)
            user = User.objects.get(pk=request.user.pk)
            random_idx = randint(0, Car.objects.count() - 1)

            current_date = datetime.now()
            future_date = current_date + timedelta(minutes=30)

            car = Car.objects.filter(booked__lte=current_date+timedelta(minutes=1))[random_idx]

            if carreserv_creation_form.is_valid():
                carreservs = carreserv_creation_form.save(commit=False)
                carreservs.client = user
                carreservs.price =  50 * carreservs.passangers + carreservs.passangers * randint(20, 70)
                carreservs.car = car
                car.booked = future_date

                print(carreserv_creation_form)
                carreservs.save()
                return redirect(
                    'main:history')

            return render(
                request=request,
                template_name='main/booking.html',
                context={'form' :carreserv_creation_form}
            )

        else:
            subject = 'Click here'
            message = "Congratulations, you have successfully subscribed to the newsletter."
            recipient = request.POST.get('email')

            send_mail(subject, message,
                      settings.DEFAULT_FROM_EMAIL, [recipient])
            
            return render(request=request, template_name='main/about.html')

class DriverView(ListView):
    model = Driver

class RateView(ListView):
    model = Rate

class RegistationView(View):
    def get(self, request):
        user_creation_form = CustomUserCreationForm()
        return render(
            request=request,
            template_name='main/registration.html',
            context={'user_form': user_creation_form,'title': 'Sign Up'}
        )

    def post(self, request):
        user_form = CustomUserCreationForm(request.POST) 
        form_errors = [f"{e}: {user_form.errors.get(e, None)[0]}" for e in user_form.errors]

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your account has been created successfuly!')
            return redirect('main:login')

        return render(
            request=request,
            template_name='main/registration.html',
            context={"user_form": user_form,'form_errors':form_errors})

class BookHistoryView(ListView):
    model = CarReserv
    template_name = 'main/book_history.html'
    context_object_name = 'reservs'
    
###############################################
###############################################

main/templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>ULOAX</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
        media="screen">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
        integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    <!--header section start -->
    <div id="index.html" class="header_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3">
                    <div class="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}"></a>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-9">
                    <div class="menu_text">
                        <ul>
                            <li><a href="{% url 'main:main' %}">Home</a></li>
                            <li><a href="{% url 'main:about' %}">About</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'main:logout' %}">Logout</a></li>
                            <li><a href="{% url 'main:booking' %}">Booking</a></li>
                            {% else %}
                            <li>
                                <a href="{% url 'main:login' %}" class="ml-5 mr-3">Login</a>
                                <a href="{% url 'main:registration' %}">Registration</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="taxis" class="taxis_section layout_padding">
        <div class="container">
            <div class="taxis_section_2">
                <div class="row">
                    <div class="col-12 mb-5">
                        <h1 class="our_text"><span style="color: #f4db31;">Login</span></h1>
                    </div>
                    <div class="col-5 mx-auto my-3">
                        <div class="row my-3">
                            {% if messages %}
                            {% for msg in messages %}
                            <div class="alert alert-success">
                                {{ msg }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <form method="POST" name="login" action="{% url 'main:login' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12 mw-100">
                                    <div class="form-group">
                                        <strong class="ml-1 font-weight-bold">
                                            <label for=""> Имя пользователя:</label>
                                        </strong>
                                        <br>
                                        {{ form.username }}
                                    </div>

                                    <div class="form-group">
                                        <strong class="ml-1 font-weight-bold">
                                            <label for=""> Пароль: </label>
                                        </strong>
                                        <br>
                                        {{ form.password }}
                                    </div>

                                    <div class="form-group">
                                        {% if form.errors %}
                                        {% for v in form.errors.values %}
                                        <div class="alert alert-danger my-2">{{ v }}</div>
                                        {% endfor %}
                                        {% endif %}
                                    </div>
                                    <br>

                                    <div class="row my-3">
                                        <div class="col">
                                            <input type="submit" class="form-control btn btn-outline-warning"
                                                value="Login" name="login">
                                        </div>
                                    </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock content %}
    <div id="contact" class="location_sectin layout_padding">
        <div class="container-fluid">
            <div class="location_main">
                <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-5">
                        <div class="download_text">DOWNLOAD<br><span style="color: #fffcf4;">OUR APP TODAY</span>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="image_7"><img src="{% static 'images/img-7.png' %}"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- download section end -->
    <!-- section footer start -->
    <div class="section_footer ">
        <div class="container">
            <div class="footer_section_2">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="account_text">Address</h2>
                        <p class="ipsum_text">It is a long established fact that a reader will be distracted by the
                            readable content of a page when looking at its layout. The point of using Lorem Ipsum is
                            that it has a more-or-less normal distribution of letters, </p>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="account_text">Links</h2>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Home</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">About</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Taxi</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Booking</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Contact Us</span></a></div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="account_text">Follow Us</h2>
                        <div class="image-icon"><img src="{% static 'images/fb-icon.png' %}"><span class="fb_text"><a
                                    href="#">Facebook</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/twitter-icon.png' %}"><span
                                class="fb_text"><a href="#">Twitter</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/in-icon.png' %}"><span class="fb_text"><a
                                    href="#">Linkedin</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/youtube-icon.png' %}"><span
                                class="fb_text"><a href="#">Youtube</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/instagram-icon.png' %}"><span
                                class="fb_text"><a href="#">Instagram</a></span></div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="adderess_text">Newsletter</h2>
                        <input type="" class="email_text" placeholder="Enter Your Email" name="Enter Your Email">
                        <button class="subscribr_bt">SUBSCRIBE</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- section footer end -->
    <!-- copyright section start -->
    <div class="copyright_section">
        <div class="container">
            <p class="copyright">2019 All Rights Reserved</p>
        </div>
    </div>

    <!-- Javascript files-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <!-- javascript -->
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });
    </script>
</body>

</html>

main/templates/main/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>ULOAX</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
        media="screen">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
        integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    <!--header section start -->
    <div id="index.html" class="header_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3">
                    <div class="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}"></a>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-9">
                    <div class="menu_text">
                        <ul>
                            <li><a href="{% url 'main:main' %}">Home</a></li>
                            <li><a href="{% url 'main:about' %}">About</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'main:booking' %}">Booking</a></li>
                            <li><a href="{% url 'main:logout' %}">Logout</a></li>
                            {% else %}
                            <li>
                                <a href="{% url 'main:login' %}" class="ml-5 mr-3">Login</a>
                                <a href="{% url 'main:registration' %}">Registration</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="taxis" class="taxis_section layout_padding">
        <div class="container my-5">
            <div class="taxis_section_2">
                <div class="row my-5">
                    <div class="col-12 my-5">
                        <h1 class="our_text">
                            <span style="color: #f4db31;">Жаль что вы уходите...</span>
                        </h1>
                        <h1 class="our_text">
                            <span style="color: #f4db31;">Ну и валите и не возвращайтесь!</span>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock content %}
    <div id="contact" class="location_sectin layout_padding">
        <div class="container-fluid">
            <div class="location_main">
                <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-5">
                        <div class="download_text">DOWNLOAD<br><span style="color: #fffcf4;">OUR APP TODAY</span>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="image_7"><img src="{% static 'images/img-7.png' %}"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- download section end -->
    <!-- section footer start -->
    <div class="section_footer ">
        <div class="container">
            <div class="footer_section_2">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="account_text">Address</h2>
                        <p class="ipsum_text">It is a long established fact that a reader will be distracted by the
                            readable content of a page when looking at its layout. The point of using Lorem Ipsum is
                            that it has a more-or-less normal distribution of letters, </p>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="account_text">Links</h2>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Home</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">About</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Taxi</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Booking</span></a></div>
                        <div class="image-icon"><img src="{% static 'images/bulit-icon.png' %}"><span class="fb_text"><a
                                    href="#">Contact Us</span></a></div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="account_text">Follow Us</h2>
                        <div class="image-icon"><img src="{% static 'images/fb-icon.png' %}"><span class="fb_text"><a
                                    href="#">Facebook</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/twitter-icon.png' %}"><span
                                class="fb_text"><a href="#">Twitter</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/in-icon.png' %}"><span class="fb_text"><a
                                    href="#">Linkedin</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/youtube-icon.png' %}"><span
                                class="fb_text"><a href="#">Youtube</a></span></div>
                        <div class="image-icon"><img src="{% static 'images/instagram-icon.png' %}"><span
                                class="fb_text"><a href="#">Instagram</a></span></div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <h2 class="adderess_text">Newsletter</h2>
                        <input type="" class="email_text" placeholder="Enter Your Email" name="Enter Your Email">
                        <button class="subscribr_bt">SUBSCRIBE</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- section footer end -->
    <!-- copyright section start -->
    <div class="copyright_section">
        <div class="container">
            <p class="copyright">2019 All Rights Reserved</p>
        </div>
    </div>

    <!-- Javascript files-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <!-- javascript -->
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });
    </script>
</body>

</html>